# Importing libraries

In [1]:
import pandas as pd
import os
import re
import math
import string
import codecs
import json
from itertools import product
from inspect import getsourcefile
from io import open
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# VADER sentiment analysis

In [22]:
sid = SentimentIntensityAnalyzer() #initializing VADER

In [34]:
tweets.drop(['Unnamed: 0'], axis=1) #removing unnamed axis

,Column,detect,scores,compound,comp_score
0,metoo,en,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos
1,i too have been a victim of sexual harrassment...,en,"{'neg': 0.193, 'neu': 0.709, 'pos': 0.098, 'co...",-0.3400,neg
2,@ realjameswoods @ twitter elizabeth perkins c...,en,"{'neg': 0.189, 'neu': 0.768, 'pos': 0.043, 'co...",-0.8126,neg
3,elizabeth perkins names james woods during mar...,en,"{'neg': 0.414, 'neu': 0.586, 'pos': 0.0, 'comp...",-0.8588,neg
4,the worst betrayal is trust betrayal metoo,en,"{'neg': 0.65, 'neu': 0.167, 'pos': 0.183, 'com...",-0.8555,neg
...,...,...,...,...,...
17165,hi metoo beauty weightloss gastrobypass florid...,en,"{'neg': 0.0, 'neu': 0.61, 'pos': 0.39, 'compou...",0.9153,pos
17166,@ tonyrobbins are you fulfilled right now tony...,en,"{'neg': 0.0, 'neu': 0.74, 'pos': 0.26, 'compou...",0.4871,pos
17167,@ sharkbaittx73 @ gbrfnt oh geez metoo even ha...,en,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos
17168,i stand with the metoo movement and believe to...,en,"{'neg': 0.181, 'neu': 0.819, 'pos': 0.0, 'comp...",-0.4767,neg
17169,hi metoo beauty weightloss gastrobypass florid...,en,"{'neg': 0.0, 'neu': 0.61, 'pos': 0.39, 'compou...",0.9153,pos

In [26]:
tweets['scores'] = tweets['Column'].apply(lambda column: sid.polarity_scores(column)) #computing polarity

In [30]:
tweets['compound']  = tweets['scores'].apply(lambda score_dict: score_dict['compound']) #computing compound polarity score

In [31]:
tweets['comp_score'] = tweets['compound'].apply(lambda c: 'pos' if c >=0 else 'neg') #classifying as pos, neg, neu

,Unnamed: 0,Column,detect,scores,compound,comp_score
0,0,metoo,en,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos
1,1,i too have been a victim of sexual harrassment...,en,"{'neg': 0.193, 'neu': 0.709, 'pos': 0.098, 'co...",-0.3400,neg
2,2,@ realjameswoods @ twitter elizabeth perkins c...,en,"{'neg': 0.189, 'neu': 0.768, 'pos': 0.043, 'co...",-0.8126,neg
3,3,elizabeth perkins names james woods during mar...,en,"{'neg': 0.414, 'neu': 0.586, 'pos': 0.0, 'comp...",-0.8588,neg
4,4,the worst betrayal is trust betrayal metoo,en,"{'neg': 0.65, 'neu': 0.167, 'pos': 0.183, 'com...",-0.8555,neg
...,...,...,...,...,...,...
17165,17165,hi metoo beauty weightloss gastrobypass florid...,en,"{'neg': 0.0, 'neu': 0.61, 'pos': 0.39, 'compou...",0.9153,pos
17166,17166,@ tonyrobbins are you fulfilled right now tony...,en,"{'neg': 0.0, 'neu': 0.74, 'pos': 0.26, 'compou...",0.4871,pos
17167,17167,@ sharkbaittx73 @ gbrfnt oh geez metoo even ha...,en,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos
17168,17168,i stand with the metoo movement and believe to...,en,"{'neg': 0.181, 'neu': 0.819, 'pos': 0.0, 'comp...",-0.4767,neg
17169,17169,hi metoo beauty weightloss gastrobypass florid...,en,"{'neg': 0.0, 'neu': 0.61, 'pos': 0.39, 'compou...",0.9153,pos

In [37]:
tweets['comp_score'].value_counts()

pos    11376
neg     5781
Name: comp_score, dtype: int64